#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ensure script runs rooted at teamham.world directory regardless of invocation cwd
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Default ENV_FILE to .env.production.local (which is git-ignored)
if [[ "${ENV_FILE}" == ".env" ]]; then
  ENV_FILE="$PROJECT_ROOT/.env.production.local"
fi

TOTAL_STAGES=7

# State tracking for credential rotation and remediation trap
ROTATION_COMPLETED="false"
VERCEL_CONFIRMED="false"

# Remediation trap: warns if runtime role password changed in Neon but Vercel wasn't updated
_remediation_trap() {
  local exit_code=$?
  if [[ "$ROTATION_COMPLETED" == "true" && "$VERCEL_CONFIRMED" == "false" ]]; then
    printf '\n'
    warn "════════════════════════════════════════════════════════════════════════"
    warn "CRITICAL REMEDIATION REQUIRED: Runtime password rotation was executed in"
    warn "Neon, but Vercel Production DATABASE_URL configuration was NOT completed."
    warn ""
    warn "Live production member traffic will fail until DATABASE_URL is updated."
    warn "Action: Copy the runtime DATABASE_URL saved in $ENV_FILE"
    warn "and update DATABASE_URL (Sensitive) in Vercel Project Settings → Env Vars."
    warn "════════════════════════════════════════════════════════════════════════"
    printf '\n'
  fi
  return $exit_code
}

trap _remediation_trap EXIT INT TERM

# In-memory variables for connection settings (never persisted to disk)
PSQL_CLIENT=""
DIRECT_DB_HOST=""
DIRECT_DB_PORT=""
DIRECT_DB_USER=""
DIRECT_DB_PASS=""
DIRECT_DB_NAME=""

POOLED_DB_HOST=""
POOLED_DB_PORT=""
POOLED_DB_USER=""
POOLED_DB_PASS=""
POOLED_DB_NAME=""

APP_RUNTIME_ROLE_PASSWORD=""
RUNTIME_DATABASE_URL=""

# ── Helper functions ──────────────────────────────────────────────────────

check_prerequisites() {
  if ! command -v node >/dev/null 2>&1; then
    warn "Node.js is required to run URL validation and crypto generation."
    return 1
  fi

  if command -v psql >/dev/null 2>&1; then
    PSQL_CLIENT="local"
  elif command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    PSQL_CLIENT="docker"
  else
    warn "Neither local 'psql' nor a running Docker daemon was detected."
    warn "Install postgresql client tools or start Docker to execute database operations."
    return 1
  fi
  return 0
}

# Executes psql without leaking passwords or connection strings to argv.
# Reads all connection parameters and secrets via environment variables.
# For Docker mode, sets environment on docker process and uses bare -e inheritance.
_exec_psql_backend() {
  local pghost="$1"; shift
  local pgport="$1"; shift
  local pguser="$1"; shift
  local pgpass="$1"; shift
  local pgdb="$1"; shift
  # Remaining args passed directly to psql

  if [[ "$PSQL_CLIENT" == "local" ]]; then
    PGHOST="$pghost" \
    PGPORT="$pgport" \
    PGUSER="$pguser" \
    PGPASSWORD="$pgpass" \
    PGDATABASE="$pgdb" \
    PGSSLMODE="require" \
    APP_RUNTIME_ROLE_PASSWORD="${APP_RUNTIME_ROLE_PASSWORD:-}" \
    psql -v ON_ERROR_STOP=1 "$@"
  elif [[ "$PSQL_CLIENT" == "docker" ]]; then
    PGHOST="$pghost" \
    PGPORT="$pgport" \
    PGUSER="$pguser" \
    PGPASSWORD="$pgpass" \
    PGDATABASE="$pgdb" \
    PGSSLMODE="require" \
    APP_RUNTIME_ROLE_PASSWORD="${APP_RUNTIME_ROLE_PASSWORD:-}" \
    docker run --rm -i \
      -e PGHOST \
      -e PGPORT \
      -e PGUSER \
      -e PGPASSWORD \
      -e PGDATABASE \
      -e PGSSLMODE \
      -e APP_RUNTIME_ROLE_PASSWORD \
      postgres:16 \
      psql -v ON_ERROR_STOP=1 "$@"
  else
    warn "No PostgreSQL client backend available."
    return 1
  fi
}

run_owner_sql_file() {
  local file_path="$1"
  local single_tx="${2:-false}"
  local psql_flags=()
  if [[ "$single_tx" == "true" ]]; then
    psql_flags+=("--single-transaction")
  fi

  _exec_psql_backend \
    "$DIRECT_DB_HOST" "$DIRECT_DB_PORT" "$DIRECT_DB_USER" "$DIRECT_DB_PASS" "$DIRECT_DB_NAME" \
    "${psql_flags[@]}" < "$file_path"
}

run_owner_query() {
  local sql="$1"
  _exec_psql_backend \
    "$DIRECT_DB_HOST" "$DIRECT_DB_PORT" "$DIRECT_DB_USER" "$DIRECT_DB_PASS" "$DIRECT_DB_NAME" \
    -t -A -q -c "$sql"
}

run_runtime_query() {
  local sql="$1"
  _exec_psql_backend \
    "$POOLED_DB_HOST" "$POOLED_DB_PORT" "app_runtime_role" "$APP_RUNTIME_ROLE_PASSWORD" "$POOLED_DB_NAME" \
    -t -A -q -c "$sql"
}

validate_and_parse_urls() {
  local direct_in="$1"
  local pooled_in="$2"

  # Pass connection strings via environment variables to avoid process table leaks
  DIRECT_INPUT="$direct_in" POOLED_INPUT="$pooled_in" node -e '
    const directStr = process.env.DIRECT_INPUT || "";
    const pooledStr = process.env.POOLED_INPUT || "";

    let directUrl, pooledUrl;
    try {
      directUrl = new URL(directStr);
    } catch (e) {
      console.error("Direct URL parsing failed: " + e.message);
      process.exit(1);
    }
    try {
      pooledUrl = new URL(pooledStr);
    } catch (e) {
      console.error("Pooled URL parsing failed: " + e.message);
      process.exit(1);
    }

    // Protocol check
    if (!["postgres:", "postgresql:"].includes(directUrl.protocol)) {
      console.error("Direct URL protocol must be postgres: or postgresql: (got " + directUrl.protocol + ")");
      process.exit(1);
    }
    if (!["postgres:", "postgresql:"].includes(pooledUrl.protocol)) {
      console.error("Pooled URL protocol must be postgres: or postgresql: (got " + pooledUrl.protocol + ")");
      process.exit(1);
    }

    // Username check
    if (directUrl.username !== "neondb_owner") {
      console.error("Direct URL username must be \"neondb_owner\" (got \"" + directUrl.username + "\")");
      process.exit(1);
    }
    if (pooledUrl.username !== "neondb_owner") {
      console.error("Pooled URL username must be \"neondb_owner\" (got \"" + pooledUrl.username + "\")");
      process.exit(1);
    }

    // Nonempty password
    if (!directUrl.password || directUrl.password.length === 0) {
      console.error("Direct URL password must not be empty");
      process.exit(1);
    }
    if (!pooledUrl.password || pooledUrl.password.length === 0) {
      console.error("Pooled URL password must not be empty");
      process.exit(1);
    }

    // Database / Pathname
    if (directUrl.pathname !== "/neondb") {
      console.error("Direct URL database pathname must be \"/neondb\" (got \"" + directUrl.pathname + "\")");
      process.exit(1);
    }
    if (pooledUrl.pathname !== "/neondb") {
      console.error("Pooled URL database pathname must be \"/neondb\" (got \"" + pooledUrl.pathname + "\")");
      process.exit(1);
    }

    // Host domain check (*.neon.tech)
    if (!directUrl.hostname.endsWith(".neon.tech")) {
      console.error("Direct URL hostname must end with \".neon.tech\" (got \"" + directUrl.hostname + "\")");
      process.exit(1);
    }
    if (!pooledUrl.hostname.endsWith(".neon.tech")) {
      console.error("Pooled URL hostname must end with \".neon.tech\" (got \"" + pooledUrl.hostname + "\")");
      process.exit(1);
    }

    // Pooler flag check
    if (directUrl.hostname.includes("-pooler")) {
      console.error("Direct URL hostname must not contain \"-pooler\" (got \"" + directUrl.hostname + "\")");
      process.exit(1);
    }
    if (!pooledUrl.hostname.includes("-pooler")) {
      console.error("Pooled URL hostname must contain \"-pooler\" (got \"" + pooledUrl.hostname + "\")");
      process.exit(1);
    }

    // Match endpoint ID and region
    const directParts = directUrl.hostname.split(".");
    const pooledParts = pooledUrl.hostname.split(".");
    if (directParts.length < 3 || pooledParts.length < 3) {
      console.error("Hostname has unexpected segment count: " + directUrl.hostname);
      process.exit(1);
    }
    if (pooledParts[0] !== `${directParts[0]}-pooler`) {
      console.error("Endpoint ID mismatch: direct is \"" + directParts[0] + "\", pooled is \"" + pooledParts[0] + "\"");
      process.exit(1);
    }
    const directDomainSuffix = directParts.slice(1).join(".");
    const pooledDomainSuffix = pooledParts.slice(1).join(".");
    if (directDomainSuffix !== pooledDomainSuffix) {
      console.error("Region/domain mismatch: direct is \"" + directDomainSuffix + "\", pooled is \"" + pooledDomainSuffix + "\"");
      process.exit(1);
    }

    // sslmode=require check
    if (directUrl.searchParams.get("sslmode") !== "require") {
      console.error("Direct URL must specify ?sslmode=require");
      process.exit(1);
    }
    if (pooledUrl.searchParams.get("sslmode") !== "require") {
      console.error("Pooled URL must specify ?sslmode=require");
      process.exit(1);
    }

    // Emit tab-delimited values for bash reader
    process.stdout.write([
      directUrl.hostname,
      directUrl.port || "5432",
      directUrl.username,
      decodeURIComponent(directUrl.password),
      directUrl.pathname.slice(1),
      pooledUrl.hostname,
      pooledUrl.port || "5432",
      pooledUrl.username,
      decodeURIComponent(pooledUrl.password),
      pooledUrl.pathname.slice(1)
    ].join("\t"));
  '
}

# ──────────────────────────────────────────────────────────────────────────
# Wizard Execution Frames
# ──────────────────────────────────────────────────────────────────────────

banner "Neon Production Database Setup Wizard"

# ── Stage 1: Prerequisites & Neon Project Setup ────────────────────────────
stage "Prerequisites & Neon Project Setup"
say "We'll verify local tools and guide you through selecting your Neon project."

if ! check_prerequisites; then
  printf '\n'
  warn "Prerequisites not satisfied. Please resolve missing tools and re-run."
  exit 1
fi

if [[ "$PSQL_CLIENT" == "local" ]]; then
  say "${GREEN}✓${RESET} Local PostgreSQL client (psql) detected."
else
  say "${GREEN}✓${RESET} Docker PostgreSQL client (postgres:16) detected."
fi
say "${GREEN}✓${RESET} Node.js runtime ($(node -v)) detected."
printf '\n'

open_url "https://console.neon.tech"
step "In the Neon Console, select or create your TeamHam production project."
step "Ensure you are on the production branch (currently named 'production') and the database is 'neondb'."
step "In the 'Connection Details' widget, set the selectors to:"
say "    - Branch:   production"
say "    - Database: neondb"
say "    - Role:     neondb_owner"
printf '\n'
step "Note the 'Pooled connection' toggle switch:"
say "    - DIRECT connection (toggle OFF): Used for DDL, migrations, and role provisioning."
say "    - POOLED connection (toggle ON):  Used for serverless runtime DATABASE_URL."
printf '\n'
note "Note: Avoid the web Neon SQL Editor because provision-runtime-role.sql uses"
note "psql meta-commands (\\getenv and \\gset) not supported in the web console."
printf '\n'
pause "Press Enter once you have your Neon Connection Details ready"

# ── Stage 2: Capture & Validate neondb_owner URLs ─────────────────────────
stage "Capture & Validate neondb_owner URLs"
say "Enter your neondb_owner connection URLs. Inputs are hidden and never printed or saved to disk."

while true; do
  printf '\n'
  step "Copy the DIRECT connection string from Neon (toggle Pooled OFF)."
  printf '  %sPaste neondb_owner DIRECT URL (hidden):%s ' "$BOLD" "$RESET"
  read -rs RAW_DIRECT_URL
  printf '\n'

  step "Copy the POOLED connection string from Neon (toggle Pooled ON)."
  printf '  %sPaste neondb_owner POOLED URL (hidden):%s ' "$BOLD" "$RESET"
  read -rs RAW_POOLED_URL
  printf '\n'

  if [[ -z "$RAW_DIRECT_URL" || -z "$RAW_POOLED_URL" ]]; then
    warn "Both Direct and Pooled URLs must be provided. Please try again."
    continue
  fi

  PARSED_VALUES=""
  if PARSED_VALUES=$(validate_and_parse_urls "$RAW_DIRECT_URL" "$RAW_POOLED_URL"); then
    IFS=$'\t' read -r \
      DIRECT_DB_HOST DIRECT_DB_PORT DIRECT_DB_USER DIRECT_DB_PASS DIRECT_DB_NAME \
      POOLED_DB_HOST POOLED_DB_PORT POOLED_DB_USER POOLED_DB_PASS POOLED_DB_NAME <<< "$PARSED_VALUES"

    say "${GREEN}✓${RESET} Direct & Pooled connection URLs validated successfully."
    note "Direct Endpoint: $DIRECT_DB_HOST"
    note "Pooled Endpoint: $POOLED_DB_HOST"
    note "Database: $DIRECT_DB_NAME | Role: $DIRECT_DB_USER | SSL: require"
    break
  else
    printf '\n'
    warn "URL validation failed. Please check the requirements above and try again."
  fi
done

pause "Press Enter to proceed to role provisioning"

# ── Stage 3: Provision / Rotate Runtime Role ──────────────────────────────
stage "Provision / Rotate Runtime Role (app_runtime_role)"
say "Generating a fresh 43-character base64url password for app_runtime_role."

APP_RUNTIME_ROLE_PASSWORD=$(node -e 'console.log(require("crypto").randomBytes(32).toString("base64url"))')
say "${GREEN}✓${RESET} Generated secure 256-bit runtime role password."
printf '\n'

say "This stage executes scripts/provision-runtime-role.sql as neondb_owner."
say "It provisions app_runtime_role with:"
say "  - NOINHERIT, NOSUPERUSER, NOCREATEDB, NOCREATEROLE, NOREPLICATION, NOBYPASSRLS"
say "  - CONNECT granted on database neondb"
say "  - USAGE granted on schema public"
say "  - CREATE revoked on schema public from PUBLIC"
say "  - Preserves existing migration grants when re-provisioning/rotating"
printf '\n'
warn "WARNING: Executing this will set or ROTATE the app_runtime_role password."
warn "If you have an existing deployment, rerunning will invalidate active runtime"
warn "connections until Vercel's DATABASE_URL is updated immediately."
printf '\n'

if ! confirm "Execute scripts/provision-runtime-role.sql as neondb_owner now?"; then
  warn "Role provisioning cancelled by user."
  exit 1
fi

say "Executing scripts/provision-runtime-role.sql against Direct connection..."
if run_owner_sql_file "$PROJECT_ROOT/scripts/provision-runtime-role.sql"; then
  ROTATION_COMPLETED="true"
  say "${GREEN}✓${RESET} Successfully provisioned/updated app_runtime_role in Neon."
else
  warn "Failed to execute scripts/provision-runtime-role.sql."
  exit 1
fi

pause "Press Enter to proceed to schema inspection and migrations"

# ── Stage 4: Query Schema State & Apply Migrations ─────────────────────────
stage "Inspect Schema State & Apply Migrations"
say "Querying current schema state in 'neondb' public schema..."

EXISTING_TABLES_RAW=$(run_owner_query "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('accounts', 'sessions', 'game_oauth_clients', 'game_oauth_subjects', 'game_authorization_codes', 'game_access_tokens') ORDER BY table_name;")

TABLE_ARRAY=()
if [[ -n "$EXISTING_TABLES_RAW" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -n "$line" ]] && TABLE_ARRAY+=("$line")
  done <<< "$EXISTING_TABLES_RAW"
fi
TABLE_COUNT=${#TABLE_ARRAY[@]}

STATE="unknown"
if [[ "$TABLE_COUNT" -eq 0 ]]; then
  STATE="clean" # Needs 0001 then 0002
elif [[ "$TABLE_COUNT" -eq 2 ]]; then
  if [[ "${TABLE_ARRAY[0]}" == "accounts" && "${TABLE_ARRAY[1]}" == "sessions" ]]; then
    STATE="migrated_0001" # Needs 0002
  fi
elif [[ "$TABLE_COUNT" -eq 6 ]]; then
  if [[ "${TABLE_ARRAY[0]}" == "accounts" && \
        "${TABLE_ARRAY[1]}" == "game_access_tokens" && \
        "${TABLE_ARRAY[2]}" == "game_authorization_codes" && \
        "${TABLE_ARRAY[3]}" == "game_oauth_clients" && \
        "${TABLE_ARRAY[4]}" == "game_oauth_subjects" && \
        "${TABLE_ARRAY[5]}" == "sessions" ]]; then
    STATE="migrated_0002" # Fully migrated
  fi
fi

if [[ "$STATE" == "unknown" ]]; then
  warn "Inconsistent or partial schema state detected!"
  warn "Found $TABLE_COUNT tables: ${TABLE_ARRAY[*]:-none}"
  warn "Aborting migration step to prevent database corruption. Please inspect manually."
  exit 1
fi

say "Current database state: ${STATE} (found $TABLE_COUNT relevant tables)."

# Migration 0001 application
if [[ "$STATE" == "clean" ]]; then
  printf '\n'
  say "Migration 0001_initial_member_system.sql creates:"
  say "  - Extension: pgcrypto"
  say "  - Tables: accounts, sessions"
  say "  - Least-privilege column and table grants to app_runtime_role"
  printf '\n'
  warn "Applying migration 0001 is an irreversible schema change."
  if ! confirm "Apply migration 0001_initial_member_system.sql in a single transaction now?"; then
    warn "Migration 0001 cancelled by user."
    exit 1
  fi
  say "Applying migrations/0001_initial_member_system.sql..."
  if run_owner_sql_file "$PROJECT_ROOT/migrations/0001_initial_member_system.sql" "true"; then
    say "${GREEN}✓${RESET} Migration 0001_initial_member_system.sql applied successfully."
    STATE="migrated_0001"
  else
    warn "Failed to apply migration 0001_initial_member_system.sql."
    exit 1
  fi
fi

# Migration 0002 application
if [[ "$STATE" == "migrated_0001" ]]; then
  printf '\n'
  say "Migration 0002_game_backend_authorization.sql creates:"
  say "  - Tables: game_oauth_clients, game_oauth_subjects, game_authorization_codes, game_access_tokens"
  say "  - Least-privilege column and table grants to app_runtime_role"
  printf '\n'
  warn "Applying migration 0002 is an irreversible schema change."
  if ! confirm "Apply migration 0002_game_backend_authorization.sql in a single transaction now?"; then
    warn "Migration 0002 cancelled by user."
    exit 1
  fi
  say "Applying migrations/0002_game_backend_authorization.sql..."
  if run_owner_sql_file "$PROJECT_ROOT/migrations/0002_game_backend_authorization.sql" "true"; then
    say "${GREEN}✓${RESET} Migration 0002_game_backend_authorization.sql applied successfully."
    STATE="migrated_0002"
  else
    warn "Failed to apply migration 0002_game_backend_authorization.sql."
    exit 1
  fi
fi

# Migration 0003 application
#
# Unlike 0001 and 0002 this migration adds a column rather than tables, so the
# table-count state machine above cannot see it. Detect the column directly.
if [[ "$STATE" == "migrated_0002" ]]; then
  HAS_USERNAME_COLUMN=$(run_owner_query "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'accounts' AND column_name = 'discord_username';")

  if [[ -z "$HAS_USERNAME_COLUMN" ]]; then
    printf '\n'
    say "Migration 0003_account_display_name.sql adds:"
    say "  - Column: accounts.discord_username (nullable, display only)"
    say "  - Least-privilege INSERT and UPDATE grants on that column to app_runtime_role"
    printf '\n'
    warn "Applying migration 0003 is an irreversible schema change."
    if ! confirm "Apply migration 0003_account_display_name.sql in a single transaction now?"; then
      warn "Migration 0003 cancelled by user."
      exit 1
    fi
    say "Applying migrations/0003_account_display_name.sql..."
    if run_owner_sql_file "$PROJECT_ROOT/migrations/0003_account_display_name.sql" "true"; then
      say "${GREEN}✓${RESET} Migration 0003_account_display_name.sql applied successfully."
      STATE="migrated_0003"
    else
      warn "Failed to apply migration 0003_account_display_name.sql."
      exit 1
    fi
  else
    STATE="migrated_0003"
  fi
fi

if [[ "$STATE" == "migrated_0003" ]]; then
  say "${GREEN}✓${RESET} All migrations (0001 through 0003) are up to date."
  note "CREATE migrations will never be rerun."
fi

pause "Press Enter to derive the runtime DATABASE_URL"

# ── Stage 5: Derive Runtime DATABASE_URL ──────────────────────────────────
stage "Derive Runtime DATABASE_URL & Write Local Environment"
say "Deriving pooled runtime connection string for app_runtime_role..."

RUNTIME_DATABASE_URL=$(POOLED_INPUT="$RAW_POOLED_URL" RUNTIME_PASS="$APP_RUNTIME_ROLE_PASSWORD" node -e '
  const u = new URL(process.env.POOLED_INPUT);
  u.username = "app_runtime_role";
  u.password = process.env.RUNTIME_PASS;
  process.stdout.write(u.toString());
')

say "${GREEN}✓${RESET} Derived pooled runtime DATABASE_URL."
note "Host: $POOLED_DB_HOST"
note "User: app_runtime_role (password: 43-char base64url secret)"
note "Preserved query parameters: sslmode=require"
printf '\n'

write_env "DATABASE_URL" "$RUNTIME_DATABASE_URL"
chmod 0600 "$ENV_FILE"
say "${GREEN}✓${RESET} Set file permissions 0600 on $ENV_FILE."
printf '\n'
note "Security Policy: Only DATABASE_URL is saved. Owner credentials and raw"
note "passwords are never saved to disk or logged."

pause "Press Enter to verify runtime permissions"

# ── Stage 6: Verify Runtime Permissions ───────────────────────────────────
stage "Verify Runtime Permissions & Security Boundaries"
say "Connecting as app_runtime_role to verify least-privilege security matrix..."

VERIFY_SQL="
SELECT
  current_user = 'app_runtime_role' AS is_runtime_user,
  NOT has_schema_privilege('app_runtime_role', 'public', 'CREATE') AS schema_create_denied,
  has_table_privilege('app_runtime_role', 'public.accounts', 'SELECT') AS accounts_select_ok,
  has_table_privilege('app_runtime_role', 'public.sessions', 'SELECT') AS sessions_select_ok,
  has_table_privilege('app_runtime_role', 'public.game_oauth_clients', 'SELECT') AS clients_select_ok,
  has_table_privilege('app_runtime_role', 'public.game_oauth_subjects', 'SELECT') AS subjects_select_ok,
  has_table_privilege('app_runtime_role', 'public.game_authorization_codes', 'SELECT') AS auth_codes_select_ok,
  has_table_privilege('app_runtime_role', 'public.game_access_tokens', 'SELECT') AS access_tokens_select_ok,
  has_column_privilege('app_runtime_role', 'public.accounts', 'discord_user_id', 'INSERT') AS accounts_insert_ok,
  has_column_privilege('app_runtime_role', 'public.accounts', 'membership_status', 'UPDATE') AS accounts_membership_update_ok,
  NOT has_table_privilege('app_runtime_role', 'public.accounts', 'DELETE') AS accounts_delete_denied,
  NOT has_column_privilege('app_runtime_role', 'public.accounts', 'access_status', 'UPDATE') AS accounts_access_status_update_denied,
  NOT has_column_privilege('app_runtime_role', 'public.accounts', 'discord_user_id', 'UPDATE') AS accounts_discord_user_id_update_denied,
  has_column_privilege('app_runtime_role', 'public.sessions', 'token_hash', 'INSERT') AS sessions_insert_ok,
  has_column_privilege('app_runtime_role', 'public.sessions', 'token_hash', 'UPDATE') AS sessions_update_ok,
  has_table_privilege('app_runtime_role', 'public.sessions', 'DELETE') AS sessions_delete_ok,
  NOT has_table_privilege('app_runtime_role', 'public.game_oauth_clients', 'INSERT') AS clients_insert_denied,
  NOT has_table_privilege('app_runtime_role', 'public.game_oauth_clients', 'UPDATE') AS clients_update_denied,
  NOT has_table_privilege('app_runtime_role', 'public.game_oauth_clients', 'DELETE') AS clients_delete_denied,
  has_column_privilege('app_runtime_role', 'public.game_oauth_subjects', 'client_id', 'INSERT') AS subjects_client_insert_ok,
  has_column_privilege('app_runtime_role', 'public.game_oauth_subjects', 'account_id', 'INSERT') AS subjects_account_insert_ok,
  has_column_privilege('app_runtime_role', 'public.game_authorization_codes', 'code_hash', 'INSERT') AS auth_codes_insert_ok,
  has_column_privilege('app_runtime_role', 'public.game_authorization_codes', 'consumed_at', 'UPDATE') AS auth_codes_update_ok,
  NOT has_table_privilege('app_runtime_role', 'public.game_authorization_codes', 'DELETE') AS auth_codes_delete_denied,
  has_column_privilege('app_runtime_role', 'public.game_access_tokens', 'token_hash', 'INSERT') AS access_tokens_insert_ok,
  has_column_privilege('app_runtime_role', 'public.game_access_tokens', 'expires_at', 'UPDATE') AS access_tokens_update_ok,
  has_table_privilege('app_runtime_role', 'public.game_access_tokens', 'DELETE') AS access_tokens_delete_ok;
"

VERIFY_RESULT=$(run_runtime_query "$VERIFY_SQL")
IFS='|' read -r \
  CHK_USER CHK_NOCREATE \
  CHK_ACC_SEL CHK_SESS_SEL CHK_CLI_SEL CHK_SUB_SEL CHK_AUTH_SEL CHK_TOK_SEL \
  CHK_ACC_INS CHK_ACC_MEM_UPD CHK_NOACC_DEL CHK_NOACC_STATUS CHK_NOACC_DISCORD \
  CHK_SESS_INS CHK_SESS_UPD CHK_SESS_DEL \
  CHK_NOCLI_INS CHK_NOCLI_UPD CHK_NOCLI_DEL \
  CHK_SUB_CLI_INS CHK_SUB_ACC_INS \
  CHK_AUTH_INS CHK_AUTH_UPD CHK_NOAUTH_DEL \
  CHK_TOK_INS CHK_TOK_UPD CHK_TOK_DEL <<< "$VERIFY_RESULT"

FAILED_CHECKS=()
[[ "$CHK_USER" == "t" ]] || FAILED_CHECKS+=("current_user is not 'app_runtime_role'")
[[ "$CHK_NOCREATE" == "t" ]] || FAILED_CHECKS+=("CREATE on schema public was not revoked")

[[ "$CHK_ACC_SEL" == "t" ]] || FAILED_CHECKS+=("accounts SELECT is missing")
[[ "$CHK_SESS_SEL" == "t" ]] || FAILED_CHECKS+=("sessions SELECT is missing")
[[ "$CHK_CLI_SEL" == "t" ]] || FAILED_CHECKS+=("game_oauth_clients SELECT is missing")
[[ "$CHK_SUB_SEL" == "t" ]] || FAILED_CHECKS+=("game_oauth_subjects SELECT is missing")
[[ "$CHK_AUTH_SEL" == "t" ]] || FAILED_CHECKS+=("game_authorization_codes SELECT is missing")
[[ "$CHK_TOK_SEL" == "t" ]] || FAILED_CHECKS+=("game_access_tokens SELECT is missing")

[[ "$CHK_ACC_INS" == "t" ]] || FAILED_CHECKS+=("accounts INSERT (discord_user_id) is missing")
[[ "$CHK_ACC_MEM_UPD" == "t" ]] || FAILED_CHECKS+=("accounts UPDATE (membership_status) is missing")
[[ "$CHK_NOACC_DEL" == "t" ]] || FAILED_CHECKS+=("accounts DELETE was not revoked")
[[ "$CHK_NOACC_STATUS" == "t" ]] || FAILED_CHECKS+=("accounts UPDATE (access_status) was not revoked")
[[ "$CHK_NOACC_DISCORD" == "t" ]] || FAILED_CHECKS+=("accounts UPDATE (discord_user_id) was not revoked")

[[ "$CHK_SESS_INS" == "t" ]] || FAILED_CHECKS+=("sessions INSERT (token_hash) is missing")
[[ "$CHK_SESS_UPD" == "t" ]] || FAILED_CHECKS+=("sessions UPDATE (token_hash) is missing")
[[ "$CHK_SESS_DEL" == "t" ]] || FAILED_CHECKS+=("sessions DELETE is missing")

[[ "$CHK_NOCLI_INS" == "t" ]] || FAILED_CHECKS+=("game_oauth_clients INSERT was not revoked")
[[ "$CHK_NOCLI_UPD" == "t" ]] || FAILED_CHECKS+=("game_oauth_clients UPDATE was not revoked")
[[ "$CHK_NOCLI_DEL" == "t" ]] || FAILED_CHECKS+=("game_oauth_clients DELETE was not revoked")

[[ "$CHK_SUB_CLI_INS" == "t" ]] || FAILED_CHECKS+=("game_oauth_subjects INSERT (client_id) is missing")
[[ "$CHK_SUB_ACC_INS" == "t" ]] || FAILED_CHECKS+=("game_oauth_subjects INSERT (account_id) is missing")

[[ "$CHK_AUTH_INS" == "t" ]] || FAILED_CHECKS+=("game_authorization_codes INSERT (code_hash) is missing")
[[ "$CHK_AUTH_UPD" == "t" ]] || FAILED_CHECKS+=("game_authorization_codes UPDATE (consumed_at) is missing")
[[ "$CHK_NOAUTH_DEL" == "t" ]] || FAILED_CHECKS+=("game_authorization_codes DELETE was not revoked")

[[ "$CHK_TOK_INS" == "t" ]] || FAILED_CHECKS+=("game_access_tokens INSERT (token_hash) is missing")
[[ "$CHK_TOK_UPD" == "t" ]] || FAILED_CHECKS+=("game_access_tokens UPDATE (expires_at) is missing")
[[ "$CHK_TOK_DEL" == "t" ]] || FAILED_CHECKS+=("game_access_tokens DELETE is missing")

if [[ ${#FAILED_CHECKS[@]} -gt 0 ]]; then
  warn "Runtime verification checks FAILED (${#FAILED_CHECKS[@]} errors):"
  for err in "${FAILED_CHECKS[@]}"; do
    warn "  - $err"
  done
  warn "Aborting: database fails closed on privilege mismatch."
  exit 1
fi

say "${GREEN}✓${RESET} Verified TLS-required connection as 'app_runtime_role' (PGSSLMODE=require)."
say "${GREEN}✓${RESET} Verified SELECT on all 6 tables (accounts, sessions, game_*)."
say "${GREEN}✓${RESET} Verified schema CREATE is denied to app_runtime_role."
say "${GREEN}✓${RESET} Verified accounts INSERT and membership UPDATE permitted; DELETE and access_status UPDATE denied."
say "${GREEN}✓${RESET} Verified sessions INSERT, UPDATE, and DELETE are permitted."
say "${GREEN}✓${RESET} Verified game_oauth_clients is read-only (SELECT permitted; INSERT, UPDATE, DELETE denied)."
say "${GREEN}✓${RESET} Verified game_oauth_subjects INSERT is permitted."
say "${GREEN}✓${RESET} Verified game_authorization_codes INSERT & UPDATE permitted; DELETE denied."
say "${GREEN}✓${RESET} Verified game_access_tokens INSERT, UPDATE, and DELETE are permitted."
say "${GREEN}✓${RESET} All 27 least-privilege security assertions passed successfully."

pause "Press Enter to proceed to Vercel production configuration"

# ── Stage 7: Configure Vercel Production Environment ──────────────────────
stage "Configure Vercel Production Environment"
say "We'll configure DATABASE_URL in Vercel for the Production environment."

VERCEL_CONFIGURED=false

if command -v vercel >/dev/null 2>&1 && vercel whoami >/dev/null 2>&1; then
  say "Vercel CLI is detected and authenticated."
  if confirm "Add/update DATABASE_URL in Vercel Production automatically via CLI?"; then
    say "Adding sensitive DATABASE_URL to Vercel Production environment..."
    # Pipe secret via stdin to prevent command-line / ps exposure
    if printf '%s' "$RUNTIME_DATABASE_URL" | vercel env add DATABASE_URL production --sensitive >/dev/null 2>&1; then
      say "${GREEN}✓${RESET} DATABASE_URL configured in Vercel Production via CLI."
      VERCEL_CONFIGURED=true
      VERCEL_CONFIRMED="true"
    else
      warn "Vercel CLI command failed. Falling back to manual configuration."
    fi
  fi
fi

if [[ "$VERCEL_CONFIGURED" == "false" ]]; then
  open_url "https://vercel.com"
  step "Open your Vercel Dashboard and select project 'teamham.world'."
  step "Navigate to: Settings → Environment Variables."
  step "Add or update the following environment variable:"
  say "    - Key:         DATABASE_URL"
  say "    - Value:       (Copied to $ENV_FILE)"
  say "    - Environment: Production (ONLY - uncheck Preview and Development)"
  say "    - Type:        Sensitive / Secret"
  printf '\n'
  step "Save the variable, then trigger a redeployment on branch 'main' to activate."
  printf '\n'
  if ! confirm "Have you saved DATABASE_URL as a sensitive variable in Vercel Production?"; then
    SKIPPED+=("Vercel Production DATABASE_URL configuration (configure manually in Vercel Settings)")
    warn "Vercel configuration skipped. Remember to configure DATABASE_URL before deploying."
  else
    say "${GREEN}✓${RESET} Vercel Production configuration confirmed."
    VERCEL_CONFIRMED="true"
  fi
fi

printf '\n'
say "Security Invariant Summary:"
note "  - DIRECT_URL and neondb_owner credentials are NEVER stored in Vercel or CI."
note "  - GitHub Actions CI remains completely secretless (AUTH_MODE=disabled)."
note "  - Production serverless runtime connects strictly as restricted app_runtime_role."

finish
